cxx_library(
  name = 'memory',
  header_namespace = 'absl/memory',
  exported_headers = subdir_glob([
    ('', '**/*.h'),
  ]),
  srcs = glob([
    '**/*.cc',
  ], excludes = glob([
    '**/*_test.cc',
  ])),
  visibility = [
    'PUBLIC',
  ],
)
