cxx_library(
  name = 'time',
  header_namespace = 'absl/time',
  exported_headers = subdir_glob([
    ('', '**/*.h'),
    ('', '**/*.inc'),
  ]),
  srcs = glob([
    '**/*.cc',
  ], excludes = glob([
    '**/*_test.cc',
  ])),
  visibility = [
    'PUBLIC',
  ],
)
